
openapi: "3.0.3"

info:
  title: "ADE Import Service - OpenAPI 3.0.3"
  version: "1.0.0"

servers:
  - url: http://localhost:3001

paths:
  /examination:
    post:
      summary: Add a new examination
      description: Add a new examination
      requestBody:
        description: Create a new examination
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExaminationRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExaminationResponse'          
        '422':
          description: Invalid input
        
        '500':
          description: Service error

  /recording:
    post:
      summary: Upload recording
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - examinationId
                - spot
                - position
                - file
              properties:
                examinationId:
                  type: string
                  format: uuid
                spot:
                  type: string
                position:
                  type: string

                # 'file' will be the field name in this multipart request
                file:
                  type: string
                  format: binary 
                  
                
      responses:
        '200':
          description: Successful operation
        '422':
          description: Invalid input
        '500':
          description: Service error



components:
  schemas:
    ExaminationRequest:
      type: object
      required:
        - dateTime
      properties:
        dateTime:
            type: string
            format: date-time
        patient:
          type: object
          properties:
            sex_at_birth:
              type: string
              enum:
                - Male
                - Female
                - N/A 
            ethnicity:
              type: string
              enum:
                - American Indian 
                - Alaska Native
                - Asian
                - African American
                - Hispanic/
                - Latino
                - Native Hawaiian or Other Pacific Islander
                - White
                - Not specified  
            age: 
              type: integer # years
            weight:
              type: integer # kg
            height:
              type: integer # meters

    ExaminationResponse:      
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
        dateTime:
            type: string
            format: date-time
